### ISSUE TITLE
Docker Service not found

### ISSUE THREAD

**Issue by wakonp** [cassinyio/SwarmSpawner#11]
Hi,
I tried out your SwarmSpawner, extending the [Deploy Docker Repo](https://github.com/jupyterhub/jupyterhub-deploy-docker) and I quickly ran into some problems. 

First of all, your example jupyter_config.py file must be updated on line 35, where you still use string args. Coming to my main problem, after install SwarmSpawner and launching the Jupyterhub as a Service in Docker Swarm everything seems to be okay. But when I login I get some weird errors which look like this:

> JupyterHub is now running at http://127.0.0.1:443/
Getting Docker service 'jupyter-3b4bd7fa0504fe5d059e1b0f2655c56b-1'
Docker service 'jupyter-3b4bd7fa0504fe5d059e1b0f2655c56b-1' is gone
Docker service not found
user_options:
Getting Docker service 'jupyter-3b4bd7fa0504fe5d059e1b0f2655c56b-1'
Docker service 'jupyter-3b4bd7fa0504fe5d059e1b0f2655c56b-1' is gone
Unhandled error starting wakonp's server: 500 Server Error: Internal Server Error ("rpc error: code = 3 desc = invalid cpu value 1e-06: Must be at least 0.001")
Getting Docker service 'jupyter-3b4bd7fa0504fe5d059e1b0f2655c56b-1'
Docker service 'jupyter-3b4bd7fa0504fe5d059e1b0f2655c56b-1' is gone
Docker service not found
Uncaught exception POST /hub/login?next= (10.255.0.2)

This error tells me two things. The JupyterHub Service can't find the generated NotebookService and that my server has an internal server error because of an invalid cpu value. Lets check out my jupyterhub_config.py file.
```
import os 
import subprocess
import os
import errno
import stat

c = get_config()
pwd = os.path.dirname(__file__)

c.JupyterHub.ip = '0.0.0.0'
c.JupyterHub.port = 443
c.JupyterHub.hub_ip = '0.0.0.0'

c.JupyterHub.spawner_class = 'cassinyspawner.SwarmSpawner'
c.JupyterHub.cleanup_servers = False

c.SwarmSpawner.start_timeout = 60 * 5
c.SwarmSpawner.jupyterhub_service_name = 'jupyterhub_jupyterhub'


c.SwarmSpawner.use_user_options = False
c.SwarmSpawner.networks = ["jupyterhub-network"]
notebook_dir = os.environ.get('NOTEBOOK_DIR') or '/home/jovyan/work'
c.SwarmSpawner.notebook_dir = notebook_dir
mounts = [{'type' : 'volume',
           'source' : 'jupyterhub-user-{username}',
           'target' : notebook_dir}]	   
c.SwarmSpawner.container_spec = {
                  'args' : ['start-singleuser.sh'],
                  'Image' :'jupyter/scipy-notebook:bb222f49222e',
                  'mounts' : mounts
          }
c.SwarmSpawner.resource_spec = {
                'cpu_limit' : 1000, # (int) – CPU limit in units of 10^9 CPU shares.
                'mem_limit' : int(512 * 1e6), # (int) – Memory limit in Bytes.
                'cpu_reservation' : 1000, # (int) – CPU reservation in units of 10^9 CPU shares.
                'mem_reservation' : int(512 * 1e6), # (int) – Memory reservation in Bytes
                }
```
As you can see I use the your config for c.SwarmSpawner.resouce_spec and I set c.SwarmSpawner.use_user_options explicit to false. So I dont understand where the error Internal Server Error ("rpc error: code = 3 desc = invalid cpu value 1e-06: Must be at least 0.001") comes from.

Some other interesting files:
Dockerfile.Jupyterhub
```
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupyterhub/jupyterhub-onbuild:0.7.2


# Install dockerspawner and its dependencies
#    oauthenticator==0.5.* \
# dockerspawner==0.7.* \
RUN /opt/conda/bin/pip install \
	jupyterhub-ldapauthenticator

RUN git clone https://github.com/cassinyio/SwarmSpawner
WORKDIR ./SwarmSpawner
RUN pip install -r requirements.txt
RUN python setup.py install
WORKDIR ..

# install docker on the jupyterhub container
RUN wget https://get.docker.com -q -O /tmp/getdocker && \
    chmod +x /tmp/getdocker && \
    sh /tmp/getdocker

# Copy TLS certificate and key
ENV SSL_CERT /srv/jupyterhub/secrets/jupyterhub.crt
ENV SSL_KEY /srv/jupyterhub/secrets/jupyterhub.key
COPY ./secrets/*.crt $SSL_CERT
COPY ./secrets/*.key $SSL_KEY
RUN chmod 700 /srv/jupyterhub/secrets && \
    chmod 600 /srv/jupyterhub/secrets/*

COPY ./userlist /srv/jupyterhub/userlist

EXPOSE 8080
EXPOSE 8081
```

Docker-compose.yml (I run it with docker stack deploy -c docker-compose.yml jupyterhub, so the service name of Jupyterhub will be jupyterhub_jupyterhub)
```
version: "3.2"

services:
  jupyterhub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
    image: walki12/jupyterhub
    container_name: jupyterhub
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: data
        target: /data
        volume: 
          nocopy: true
    ports:
      - "443:443"
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

volumes:
  data:
    external:
      name: jupyterhub-data

networks:
  default:
    external: 
      name: jupyterhub-network
```
The Volume jupyterhub-data is available and the jupyterhub-network is an attachable overlay network. 

> Docker version 17.06.0-ce, build 02c1d87

I don't understand why this configuration does not work correctly and I really appreciate some decent explanation for this scenario.
